## Numpy Tutorials
NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

## What is an array
An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

## Features
- Faster than Python lists for numerical operations

- Supports multidimensional arrays

- Provides mathematical, statistical, and linear algebra functions

- Works well with other libraries like Pandas, Matplotlib, and Scikit-learn

| Function                | Description                                  | Example                      |
| ----------------------- | -------------------------------------------- | ---------------------------- |
| `np.array()`            | Create a NumPy array                         | `np.array([1, 2, 3])`        |
| `np.zeros()`            | Create an array filled with zeros            | `np.zeros((3,3))`            |
| `np.ones()`             | Create an array filled with ones             | `np.ones((2,4))`             |
| `np.arange()`           | Create array with evenly spaced values       | `np.arange(0, 10, 2)`        |
| `np.linspace()`         | Create evenly spaced numbers between a range | `np.linspace(1, 5, 10)`      |
| `np.reshape()`          | Change shape of array                        | `arr.reshape(2,3)`           |
| `np.sum()`              | Sum of elements                              | `np.sum(arr)`                |
| `np.mean()`             | Mean value                                   | `np.mean(arr)`               |
| `np.max()` / `np.min()` | Maximum & Minimum value                      | `np.max(arr)`, `np.min(arr)` |
| `np.dot()`              | Dot product of two arrays                    | `np.dot(a, b)`               |


In [ ]:
import numpy as np

# Creating NumPy array
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)

# Array of zeros
zeros_arr = np.zeros((2, 3)) # 2-rows, 3-cols
print("Zeros Array:\n", zeros_arr)

# Array of ones
ones_arr = np.ones((2, 3))
print("Ones Array:\n", ones_arr)

# Range of numbers
range_arr = np.arange(0, 10, 2)
print("Range Array:", range_arr)

# Reshaping array
reshaped = np.arange(1, 7).reshape(2, 3)
print("Reshaped Array:\n", reshaped)


Array: [1 2 3 4 5]
Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]
Range Array: [0 2 4 6 8]
Reshaped Array:
 [[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np

data = np.array([10, 20, 30, 40, 50])

print("Sum:", np.sum(data))
print("Mean:", np.mean(data))
print("Max:", np.max(data))
print("Min:", np.min(data))
print("Standard Deviation:", np.std(data))

# Using linspace
print("Linspace:", np.linspace(0, 1, 5)) # start point, End Point, No.s

# Matrix multiplication
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print("Dot Product:\n", np.dot(a, b))


Sum: 150
Mean: 30.0
Max: 50
Min: 10
Standard Deviation: 14.142135623730951
Linspace: [0.   0.25 0.5  0.75 1.  ]
Dot Product:
 [[19 22]
 [43 50]]
