## Numpy Tutorials
NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

## What is an array
An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

## Features
- Faster than Python lists for numerical operations

- Supports multidimensional arrays

- Provides mathematical, statistical, and linear algebra functions

- Works well with other libraries like Pandas, Matplotlib, and Scikit-learn

| Function                | Description                                  | Example                      |
| ----------------------- | -------------------------------------------- | ---------------------------- |
| `np.array()`            | Create a NumPy array                         | `np.array([1, 2, 3])`        |
| `np.zeros()`            | Create an array filled with zeros            | `np.zeros((3,3))`            |
| `np.ones()`             | Create an array filled with ones             | `np.ones((2,4))`             |
| `np.arange()`           | Create array with evenly spaced values       | `np.arange(0, 10, 2)`        |
| `np.linspace()`         | Create evenly spaced numbers between a range | `np.linspace(1, 5, 10)`      |
| `np.reshape()`          | Change shape of array                        | `arr.reshape(2,3)`           |
| `np.sum()`              | Sum of elements                              | `np.sum(arr)`                |
| `np.mean()`             | Mean value                                   | `np.mean(arr)`               |
| `np.max()` / `np.min()` | Maximum & Minimum value                      | `np.max(arr)`, `np.min(arr)` |
| `np.dot()`              | Dot product of two arrays                    | `np.dot(a, b)`               |


In [1]:
import numpy as np

# Creating NumPy array
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)

# Array of zeros
zeros_arr = np.zeros((2, 3)) # 2-rows, 3-cols
print("Zeros Array:\n", zeros_arr)

# Array of ones
ones_arr = np.ones((2, 3))
print("Ones Array:\n", ones_arr)

# Range of numbers
range_arr = np.arange(0, 10, 2)
print("Range Array:", range_arr)

# Reshaping array
reshaped = np.arange(1, 7).reshape(2, 3)
print("Reshaped Array:\n", reshaped)


Array: [1 2 3 4 5]
Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]
Range Array: [0 2 4 6 8]
Reshaped Array:
 [[1 2 3]
 [4 5 6]]


In [2]:
import numpy as np

data = np.array([10, 20, 30, 40, 50])

print("Sum:", np.sum(data))
print("Mean:", np.mean(data))
print("Max:", np.max(data))
print("Min:", np.min(data))
print("Standard Deviation:", np.std(data))

# Using linspace
print("Linspace:", np.linspace(0, 1, 5)) # start point, End Point, No.s

# Matrix multiplication
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print("Dot Product:\n", np.dot(a, b))


Sum: 150
Mean: 30.0
Max: 50
Min: 10
Standard Deviation: 14.142135623730951
Linspace: [0.   0.25 0.5  0.75 1.  ]
Dot Product:
 [[19 22]
 [43 50]]


In [3]:
#Just practice purpose
import numpy as np

In [4]:
my_list=[1,2,3,4,5]
arr=np.array(my_list)
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [5]:
#single array
arr

array([1, 2, 3, 4, 5])

In [6]:
arr.shape

(5,)

In [7]:
#MultiNested Array
my_list1=[1,2,3,4,5]
my_list2=[2,3,5,4,6]
my_list3=[7,9,3,4,5]
arr1=np.array([my_list1,my_list2,my_list3])
arr1



array([[1, 2, 3, 4, 5],
       [2, 3, 5, 4, 6],
       [7, 9, 3, 4, 5]])

In [8]:
arr1.shape

(3, 5)

In [9]:
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 5, 4],
       [6, 7, 9],
       [3, 4, 5]])

## Indexing

In [10]:
## Accessing the array elements

arr

array([1, 2, 3, 4, 5])

In [11]:
arr[2]

np.int64(3)

In [12]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 5, 4, 6],
       [7, 9, 3, 4, 5]])

In [13]:
arr1[1:,:2]

array([[2, 3],
       [7, 9]])

In [14]:
arr1[:2,:2]

array([[1, 2],
       [2, 3]])

In [15]:
arr

array([1, 2, 3, 4, 5])

In [16]:
arr[3:]=100

In [17]:
arr

array([  1,   2,   3, 100, 100])

In [18]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 5, 4, 6],
       [7, 9, 3, 4, 5]])

In [19]:
arr1.reshape(1,15)

array([[1, 2, 3, 4, 5, 2, 3, 5, 4, 6, 7, 9, 3, 4, 5]])

In [26]:
arr2=np.arange(0,10,2) # (start,stop,step)
arr2

array([0, 2, 4, 6, 8])

In [27]:
np.linspace(1,45,50)

array([ 1.        ,  1.89795918,  2.79591837,  3.69387755,  4.59183673,
        5.48979592,  6.3877551 ,  7.28571429,  8.18367347,  9.08163265,
        9.97959184, 10.87755102, 11.7755102 , 12.67346939, 13.57142857,
       14.46938776, 15.36734694, 16.26530612, 17.16326531, 18.06122449,
       18.95918367, 19.85714286, 20.75510204, 21.65306122, 22.55102041,
       23.44897959, 24.34693878, 25.24489796, 26.14285714, 27.04081633,
       27.93877551, 28.83673469, 29.73469388, 30.63265306, 31.53061224,
       32.42857143, 33.32653061, 34.2244898 , 35.12244898, 36.02040816,
       36.91836735, 37.81632653, 38.71428571, 39.6122449 , 40.51020408,
       41.40816327, 42.30612245, 43.20408163, 44.10204082, 45.        ])

In [28]:
arr

array([  1,   2,   3, 100, 100])

In [32]:
arr3=arr

In [34]:
arr3[3:]=555
print(arr3)

[  1   2   3 555 555]


In [35]:
print(arr)
arr3[3:]=555
print(arr3)

[  1   2   3 555 555]
[  1   2   3 555 555]


In [38]:
arr

array([  1,   2,   3, 555, 555])

In [43]:
#conditions that are very useful for EDA
val=4
arr[arr<4]

array([1, 2, 3])

In [44]:
#create arrays and reshape
np.arange(0,20).reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [48]:
np.ones(5, dtype=float)

array([1., 1., 1., 1., 1.])

In [49]:
np.ones((2,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

## Random Distribution

In [54]:
np.random.rand(4,40)# Store random values in a given shape

array([[0.288509  , 0.32586518, 0.64866884, 0.54867156, 0.07419678,
        0.50393373, 0.06917038, 0.59430604, 0.17335125, 0.63634455,
        0.94470363, 0.09306762, 0.68008259, 0.05526364, 0.65930723,
        0.60842015, 0.27590841, 0.76209559, 0.49794717, 0.78028789,
        0.62937305, 0.64299391, 0.03450611, 0.11327057, 0.94319854,
        0.75950805, 0.50265255, 0.91862472, 0.81406474, 0.05269097,
        0.90013845, 0.56418969, 0.643106  , 0.56644393, 0.4682378 ,
        0.56764717, 0.88959271, 0.7344262 , 0.86533383, 0.88485612],
       [0.65840362, 0.26401097, 0.88184086, 0.48694963, 0.44021198,
        0.51521562, 0.18962648, 0.70205518, 0.85001742, 0.47884612,
        0.17419432, 0.75264511, 0.03809818, 0.20267909, 0.94754231,
        0.73226156, 0.37591989, 0.65083432, 0.89628636, 0.47923108,
        0.78083995, 0.31876377, 0.43791047, 0.3445472 , 0.40104136,
        0.65100047, 0.104345  , 0.84774573, 0.25453144, 0.1763558 ,
        0.5280635 , 0.11565677, 0.62585161, 0.8

In [56]:
np.random.randint(0,100,8).reshape(2,4)

array([[43,  6, 82,  0],
       [95, 85, 14, 34]], dtype=int32)

In [58]:
np.random.random_sample((1,5))

array([[0.51240569, 0.0489044 , 0.32118063, 0.5829602 , 0.69255679]])